@baseURL = http://localhost:8080
POST {{baseURL}}/user
Content-Type: application/json

{
    "name": "Sicrano",
    "email": "email2@email.com",
    "password": "123456",
    "role": "admin"
}
###



# @name loginUser
POST {{baseURL}}/sessions
Content-Type: application/json

{
    "email": "email4@email.com",
    "password": "123456"
}
###
@tokenUser = {{loginUser.response.body.token}}



POST {{baseURL}}/punch-clock
Content-Type: application/json
Authorization: Bearer {{tokenUser}}

{
    "type":"checkIn"
}
###



GET {{baseURL}}/punch-clock/history
Content-Type: application/json
Authorization: Bearer {{tokenUser}}
###



GET {{baseURL}}/admin/punch-clock?startDate=2025-05-30
Content-Type: application/json
Authorization: Bearer {{tokenUser}}
###



GET {{baseURL}}/admin/reports
Content-Type: application/json
Authorization: Bearer {{tokenUser}}